export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Conflict
  CONFLICT: 'CONFLICT',

  // Department
  DEPARTMENT_NAME_ALREADY_EXISTS: 'DEPARTMENT_NAME_ALREADY_EXISTS',
  DEPARTMENT_NOT_EMPTY: 'DEPARTMENT_NOT_EMPTY',

  // User
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  ADMIN_CANNOT_DISABLE_SELF: 'ADMIN_CANNOT_DISABLE_SELF',
  USER_PENDING_LEAVE_EXISTS: 'USER_PENDING_LEAVE_EXISTS',
  MANAGER_MUST_BE_REMOVED_BEFORE_DISABLE: 'MANAGER_MUST_BE_REMOVED_BEFORE_DISABLE',
  USER_IS_CURRENT_MANAGER: 'USER_IS_CURRENT_MANAGER',
  ADMIN_SELF_PASSWORD_RESET_NOT_ALLOWED: 'ADMIN_SELF_PASSWORD_RESET_NOT_ALLOWED',

  // Manager
  MANAGER_HAS_PENDING_LEAVE: 'MANAGER_HAS_PENDING_LEAVE',
  MANAGER_HAS_PENDING_APPROVAL_TASKS: 'MANAGER_HAS_PENDING_APPROVAL_TASKS',
  INVALID_MANAGER_CANDIDATE: 'INVALID_MANAGER_CANDIDATE',

  // Internal
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = keyof typeof ErrorCode;
