export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Conflict
  CONFLICT: 'CONFLICT',

  // Department
  DEPARTMENT_NAME_ALREADY_EXISTS: 'DEPARTMENT_NAME_ALREADY_EXISTS',
  DEPARTMENT_NOT_EMPTY: 'DEPARTMENT_NOT_EMPTY',

  // User
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  ADMIN_CANNOT_DISABLE_SELF: 'ADMIN_CANNOT_DISABLE_SELF',
  USER_PENDING_LEAVE_EXISTS: 'USER_PENDING_LEAVE_EXISTS',
  MANAGER_MUST_BE_REMOVED_BEFORE_DISABLE: 'MANAGER_MUST_BE_REMOVED_BEFORE_DISABLE',
  USER_IS_CURRENT_MANAGER: 'USER_IS_CURRENT_MANAGER',
  ADMIN_SELF_PASSWORD_RESET_NOT_ALLOWED: 'ADMIN_SELF_PASSWORD_RESET_NOT_ALLOWED',

  // Manager
  MANAGER_HAS_PENDING_LEAVE: 'MANAGER_HAS_PENDING_LEAVE',
  MANAGER_HAS_PENDING_APPROVAL_TASKS: 'MANAGER_HAS_PENDING_APPROVAL_TASKS',
  INVALID_MANAGER_CANDIDATE: 'INVALID_MANAGER_CANDIDATE',

  // Announcement
  ANNOUNCEMENT_STATE_NOT_EDITABLE: 'ANNOUNCEMENT_STATE_NOT_EDITABLE',
  ANNOUNCEMENT_STATE_NOT_DELETABLE: 'ANNOUNCEMENT_STATE_NOT_DELETABLE',
  ANNOUNCEMENT_ALREADY_PUBLISHED: 'ANNOUNCEMENT_ALREADY_PUBLISHED',
  ANNOUNCEMENT_NOT_PUBLISHED: 'ANNOUNCEMENT_NOT_PUBLISHED',
  ANNOUNCEMENT_ALREADY_WITHDRAWN: 'ANNOUNCEMENT_ALREADY_WITHDRAWN',
  ANNOUNCEMENT_NOT_AVAILABLE: 'ANNOUNCEMENT_NOT_AVAILABLE',

  // Leave
  LEAVE_NOT_FOUND: 'LEAVE_NOT_FOUND',
  LEAVE_DATE_INVALID: 'LEAVE_DATE_INVALID',
  LEAVE_DATE_BEFORE_TODAY: 'LEAVE_DATE_BEFORE_TODAY',
  LEAVE_DURATION_EXCEEDED: 'LEAVE_DURATION_EXCEEDED',
  LEAVE_DATE_OVERLAP: 'LEAVE_DATE_OVERLAP',
  LEAVE_APPROVER_NOT_AVAILABLE: 'LEAVE_APPROVER_NOT_AVAILABLE',
  LEAVE_SELF_APPROVAL_NOT_ALLOWED: 'LEAVE_SELF_APPROVAL_NOT_ALLOWED',
  LEAVE_STATE_NOT_ALLOWED: 'LEAVE_STATE_NOT_ALLOWED',
  LEAVE_STATE_CONFLICT: 'LEAVE_STATE_CONFLICT',
  LEAVE_APPROVER_INVALID: 'LEAVE_APPROVER_INVALID',
  LEAVE_NO_DEPARTMENT: 'LEAVE_NO_DEPARTMENT',
  LEAVE_DEPARTMENT_NO_MANAGER: 'LEAVE_DEPARTMENT_NO_MANAGER',
  APPROVAL_NOT_ASSIGNED: 'APPROVAL_NOT_ASSIGNED',

  // Knowledge
  KNOWLEDGE_ARTICLE_NOT_FOUND: 'KNOWLEDGE_ARTICLE_NOT_FOUND',
  KNOWLEDGE_ARTICLE_FORBIDDEN: 'KNOWLEDGE_ARTICLE_FORBIDDEN',
  KNOWLEDGE_ARTICLE_STATE_NOT_ALLOWED: 'KNOWLEDGE_ARTICLE_STATE_NOT_ALLOWED',
  KNOWLEDGE_CATEGORY_NOT_AVAILABLE: 'KNOWLEDGE_CATEGORY_NOT_AVAILABLE',
  KNOWLEDGE_COMMENT_NOT_FOUND: 'KNOWLEDGE_COMMENT_NOT_FOUND',
  KNOWLEDGE_COMMENT_FORBIDDEN: 'KNOWLEDGE_COMMENT_FORBIDDEN',
  KNOWLEDGE_COMMENT_ALREADY_DELETED: 'KNOWLEDGE_COMMENT_ALREADY_DELETED',
  KNOWLEDGE_CATEGORY_NAME_EXISTS: 'KNOWLEDGE_CATEGORY_NAME_EXISTS',
  KNOWLEDGE_CATEGORY_IN_USE: 'KNOWLEDGE_CATEGORY_IN_USE',
  KNOWLEDGE_MODERATION_REASON_REQUIRED: 'KNOWLEDGE_MODERATION_REASON_REQUIRED',
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  AI_RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',
  AI_REQUEST_IN_PROGRESS: 'AI_REQUEST_IN_PROGRESS',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_QUERY_NO_RESULTS: 'AI_QUERY_NO_RESULTS',

  // Internal
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = keyof typeof ErrorCode;
